export const STYLE_PROMPTS = {

  outdoor: [
    "TOK, golden hour outdoor portrait, Canon EOS R5 85mm f/1.2 at wide open with subtle chromatic aberration on out-of-focus highlights, warm backlight creating Rembrandt triangle shadow pattern on the far cheek, Kodak Portra 400 film emulation with warm skin tones and pastel greens, skin showing natural subsurface scattering at the nostrils and ear tips where light passes through tissue, sharp iris focus with twin catchlights from the golden sun, individual hair strands separated by rim light creating a soft halo effect, atmospheric haze separating subject from the sunlit mountain background, slight lens flare catching the left edge of frame, 4:1 key-to-fill ratio for dimensional depth",

    "TOK, beach portrait at sunset shot from slightly low angle, Nikon Z9 70-200mm f/2.8 at 200mm with strong telephoto compression flattening the perspective, warm orange sidelight with the sun just above the horizon creating a 3-stop dynamic range from highlights to shadow, Fuji Pro 400H color profile with cool skin tones and signature muted reds, visible pore structure especially on the nose with natural skin oil speculars, Duchenne smile with crinkling at the corners of the eyes, ocean background throwing creamy bokeh with characteristically round specular highlights at f/2.8, wind-tousled hair with individual strands catching golden rim light, lens hood shadow creating a natural vignette",

    "TOK, urban street candid portrait in late afternoon, Leica M11 50mm f/0.95 producing dreamy swirly bokeh in the city background, loop lighting pattern with the nose shadow just touching the corner of the lip, warm mixed ambient light with slight tungsten cast on the shadow side, Kodak Tri-X black and white conversion with heavy grain structure from pushing to 1600, half-lidded relaxed gaze directed just past the camera creating an intimate voyeuristic feel, accurate skin with natural red capillary detail visible in the cheeks, fine vellus hairs (peach fuzz) catching the sidelight, deep rich blacks characteristic of pushed Tri-X, 35mm documentary framing with the subject slightly off-center",

    "TOK, atmospheric rooftop portrait just after sunset, Sony A7IV 85mm f/1.4 with characteristically smooth bokeh and fast focus falloff, split lighting with a 3:1 ratio creating dramatic depth on one side of the face, city skyline with early evening blue hour ambient light mixing with warm artificial interior light leaking from windows behind, skin with natural color variation showing slightly pinker cheeks and a subtly paler nose bridge, direct confident gaze with a slight chin dip creating a warm approachable expression, fine fabric structure visible on clothing with natural creases and folds at the elbows, environmental evening fog catching the low ambient light and creating visible volumetric haze layers between the subject and city lights",

    "TOK, hiking trail portrait in open shade, Sony A7III 35mm f/1.8 with noticeable corner vignette wide open naturally drawing the eye to the face, butterfly lighting created by soft overcast sky acting as a giant natural softbox with a subtle shadow directly under the nose, Ilford HP5+ black and white with classic silver gelatin texture and smooth mid-tone separation from Zone V to Zone VIII, skin with natural matte finish showing fine pore structure under diffuse light with no specular hotspots, genuine authentic smile with natural eye crinkle and slight crow's feet texture, sharp focus on the near eye with the far eye gently softening into acceptable depth at f/1.8, muscular fiber detail visible if shirtless or fabric texture on clothing, environmental detail sharp enough to locate while remaining clearly secondary to the face",
  ],

  professional: [
    "TOK, premium corporate studio headshot, Canon EOS R5 50mm f/2.8 macro lens with exceptional flat-field sharpness across the entire face, large octabox positioned for butterfly lighting from above with a strip softbox fill at f/5.6 eliminating shadow wrap-around, neutral grey seamless background with the subject well-separated by precise rim lighting on both shoulders, Hasselblad H6D color science emulation with natural skin rendering and medium-format three-dimensional pop, direct warm confident eye contact with a subtle Mona Lisa half-smile, skin with accurate subsurface scattering showing slight translucency at the ears where light passes through the tissue, razor-sharp iris detail with the catchlight precisely positioned at 10 o'clock in both eyes, executive-quality neutral color grade with lifted black point for a modern corporate look, natural hair with visible individual strands and scalp detail at the part",

    "TOK, modern corporate portrait with environmental office context, Sony A7IV 85mm f/1.4 at f/2.8 for a balance of subject isolation and background readability, large north-facing window providing soft directional light from the left with a subtle kicker from an accent light on the right, warm wooden tones in the blurred open-plan office background providing a complementary color contrast against the subject's skin, skin with natural micro-contrast showing individual vellus hairs catching the window light, approachable genuine smile with the eyes fully engaged (Duchenne marker visible), fine fabric weave visible on a tailored blazer with natural shoulder drape, subtle cream/matte black point crushing for a modern editorial film look, professional accessories in focus like a subtle watch or simple necklace adding personality without distraction",

    "TOK, business casual executive portrait, Nikon Z7II 85mm f/1.8 S-line with its characteristically neutral color rendering and zero chromatic aberration, large soft key light from above combined with a white V-flat fill creating a 2:1 ratio that wraps light gently around both cheeks, clean pure white background with the subject's shadow falling directly below at a 45-degree angle, Kodak Ektar 100 color emulation with deeply saturated skin tones and warm flesh tones that create a vibrant professional energy, direct confident eye contact with a subtle knowing smirk, skin texture clearly visible with natural pore structure and light matte finish, individual eyebrow hairs distinct and separated by the key light, fine catchlights precisely at 11 and 1 o'clock in the iris, clean professional color grade with slightly warm skin tones and neutral cool-toned clothing separation",

    "TOK, outdoor architectural corporate portrait, Canon R6 85mm f/1.2L with its signature creamy defocus and dreamy background rendering, open shade from a modern building overhang creating even soft illumination with a natural 3-stop range from the lit foreground to shadowed background, contemporary glass-and-steel building providing a blurred architectural context that grounds the subject in a professional environment without competing for attention, skin with natural color variation and proper normalization that keeps the face neutral even under mixed light sources that have different color temperatures, genuine approachable smile with relaxed confident body language reflected in open shoulders slightly turned toward the camera, sharp iris detail with the architecture reflecting as tiny rectangles in the catchlights, heavy clothing texture visible from a high-quality merino wool sweater or structured cotton shirt, editorial portrait color grade with muted backgrounds and slightly saturated skin tones",

    "TOK, high-end commercial portrait, Sony A1 135mm f/1.8 GM with extreme telephoto compression bringing the background close and flattening facial features beautifully, dramatic short lighting with a large rectangular softbox creating a precise key with a grid spot providing accent edge light on the shadowed shoulder, dark charcoal seamless background creating a full 5-stop range from the deep shadow to the lit cheek, medium format digital color profile with 15-stop dynamic range emulation and diffuse highlight roll-off, strong confident direct expression with relaxed eyebrows and centered piercing eye contact, deep sharp focus on both eyes with the nose and ears gently softening into the depth-of-field falloff, visible skin texture and pores at full resolution with natural skin grain structure, subtle cinematic color grade with warm highlights leaning into amber and cool shadows leaning into teal, premium suit fabric showing intricate weave pattern under the key light, museum-quality portrait lighting that sells",
  ],

  lifestyle: [
    "TOK, candid coffee shop moment with documentary authenticity, Fujifilm X-T5 35mm f/1.4 with its characteristically imperfect rendering and charming optical character, warm ambient cafe tungsten light from overhead fixtures mixing with cool blue window daylight creating a natural color temperature contrast, the subject mid-laugh with a genuine unposed expression caught in a natural moment, blurred cafe background with warm bokeh light discs from pendant fixtures creating a cozy atmosphere, skin showing natural mixed-lighting color variation where the warm tungsten side is slightly amber and the window side is slightly neutral, 35mm environmental framing that includes a blurred coffee cup and saucer at the bottom edge of frame adding to the candid feel, Kodak Portra 800 pushed one stop for increased grain and contrast characteristic of available-light candids, individual hair strands reflecting the overhead warm light against the cooler window-side shadows, documentary photography color grade with slightly desaturated shadows and warm highlights",

    "TOK, kitchen lifestyle portrait in warm mid-afternoon, Sony A7IV 50mm f/1.8 at f/2.2 with excellent balance of subject sharpness and background separation, soft natural window light from the side at a 45-degree angle creating a gentle Rembrandt shadow on the far cheek, warm neutral kitchen tones with wood countertops and brass fixtures providing an upscale but lived-in atmosphere, relaxed happy expression with a slight head tilt suggesting easy confidence and comfort, skin with natural indoor light rendering showing subtle warm undertones, individual food preparation details like flour dust or a cutting board slightly blurred in the foreground adding environmental storytelling, sharp eye focus with single catchlight from the window at 10 o'clock, fine texture on skin under the direct window light showing natural pore smoothness, editorial lifestyle magazine color grade with warm ambient tones and slightly lifted shadows for a bright airy feel, relaxed authentic body language with one hand holding a coffee cup near the chest",

    "TOK, reading in a sunlit modern living room, Canon EOS R5 85mm f/1.4L with fast focus falloff isolating the subject from the interior background, gentle short lighting with the window positioned behind and to the right of the subject creating soft wrap-around illumination on the near side, warm mid-afternoon light streaming through sheer curtains creating soft texture on the floor and furniture, relaxed authentic expression looking slightly downward at a book with a soft natural half-smile, skin with beautiful warm directional light emphasizing cheekbone structure and nose bridge, sharp visible catchlights from the large window reflected in the iris as rectangles, fine fabric detail on a casual linen shirt with natural wrinkles adding tactile authenticity, book with readable title spine and textured paper pages, warm cozy atmosphere with a dark wood bookshelf slightly blurred behind, editorial lifestyle photography with natural golden color grading and subtle warmth throughout the scene",

    "TOK, indoor gym candid portrait against mirrored walls, Nikon Z6II 35mm f/1.8 capturing a wide environmental context within the narrow gym space, bright overhead gym LED lighting combined with a large window creating a high-energy mixed light setup, active mid-movement expression with natural exertion shown through slightly parted lips and engaged facial muscles, skin with a natural healthy post-workout glow showing subtle perspiration and a light pink flush in the cheeks, sharp eye focus with the mirror reflection creating an interesting double-composition showing the photographer in the background, visible skin texture with natural moisture and shine under the bright uniform gym lights, fine details like sweat on the temples and a slightly damp shirt adding authenticity, blurred gym equipment in the background providing context, sports editorial photography style with high contrast and vivid natural colors, authentic mid-workout moment never a posed flexing shot",

    "TOK, dinner party candid on a warm summer evening, Sony A7III 85mm f/1.4 at f/2 for perfect depth at this focal length, warm golden evening ambient light filtering through trees combined with strategic warm candle glow creating pools of warm accent light across the scene, genuine laugh caught mid-conversation with friends softly blurred in the background providing context, natural warm skin tones rendered under mixed light with the subtle orange cast of candlelight on the face, sharp face focus with catchlights visible from both the sunset ambient and the candle source, fine dinner table details like wine glasses with candle reflections and small plates at the edges of the frame, natural skin texture with warm golden skin tones and accurate red tones in the lips under the warm light, documentary social photography color grade with rich warm tones and deep shadows, outdoor string lights creating circular bokeh patterns across the background frame",
  ],

  travel: [
    "TOK, iconic landmark travel portrait with strong environmental context, Canon EOS R5 35mm f/2 with wide-angle environmental storytelling that keeps the landmark recognizable and the subject dominant in the foreground, bright natural midday sun with the subject positioned with the sun at 45 degrees to create dimension while the landmark is backlit creating a natural rim on the famous structure, vivid destination colors with deep blue sky and warm terracotta architecture, Kodak Ektar 100 emulation for saturated blues and warm flesh tones with its characteristic deep contrast, genuine adventure smile with the eyes squinting slightly in the bright sun creating an authentic outdoor expression, sharp eye detail with a small specular catchlight from the bright sky, visible skin texture with natural sun exposure tones, slight atmospheric haze in the distance separating the subject from the background landmark, National Geographic travel portrait color grade with punchy contrast and vivid saturated primaries, the wind moving through the subject's hair adds motion and life to the frame",

    "TOK, European street portrait in golden hour, Sony A7IV 50mm f/1.4 at f/2 for ideal depth-of-field balance, warm golden hour sidelight from the left creating a dramatic 3:1 lighting ratio on the face, historic cobblestone street and classic architecture heavily blurred in the background creating a timeless European atmosphere, relaxed confident traveler expression with a genuine curious half-smile looking slightly past the camera at something interesting, skin with warm golden skin tones rendered beautifully under the low-angle golden sun with natural orange-warm undertones, sharp catchlights at 9 o'clock in the iris from the sun creating a bright sparkle in the eyes, fine skin detail on the bridge of the nose and cheekbones where the light hits directly, clothing with natural fabric texture and a travel-appropriate casual look, atmospheric golden haze in the background with sun flare occasionally catching the lens, travel documentary color grade with warm golden tones and slightly desaturated shadows",

    "TOK, tropical beach portrait in soft midday light, Nikon Z9 85mm f/1.8 with excellent subject isolation from the vibrant background, bright tropical daylight diffused through high-altitude thin cloud creating a natural softbox effect that eliminates harsh shadows, vibrant turquoise ocean water in the background with gentle wave texture creating a natural dynamic background pattern, genuine happy relaxed expression with open confident body language and arms naturally at the sides or slightly raised, sharp iris focus with strong catchlights from the bright overcast sky reflected as large soft highlights in the eyes, natural skin texture with healthy sun-kissed tones and a subtle sheen on the shoulders and décolletage, individual wet or dry hair strands separated by the ambient light, subtle lens flare from the tropical sun adding warmth to the frame, travel magazine editorial color grade with vibrant ocean blues and natural warm skin tones that look like a premium vacation campaign",

    "TOK, mountain summit portrait at sunrise, Canon R6 24mm f/2.8 wide-angle environmental portrait showing the vast landscape scale while keeping the face prominent in the lower third, dramatic natural sunrise golden light from the side creating a spectacular rim light that separates the subject from the dimmer pre-dawn landscape, sweeping mountain vista with atmospheric layering creating five distinct depth planes from the subject to the horizon, authentic exhausted-but-triumphant explorer expression with rosy cheeks and slightly wind-reddened skin from the cold altitude, wind-movement clearly visible in the hair with loose strands blowing across the face, sharp face detail with visible cold-induced skin texture and natural capillary flush, frozen breath vapor or early sunlight illuminating water droplets on the skin, adventure documentary color grade with vivid saturated natural colors and deep rich shadows, rule of thirds composition with the subject occupying the lower third and the vast landscape filling the rest of the frame, light frozen breath mist visible in front of the face from the cold air",

    "TOK, vibrant night market travel portrait, Sony A7S III 35mm f/1.4 specifically chosen for excellent low-light performance and fast aperture, warm mixed tungsten and neon street light creating a complex multi-color temperature scene with warm orange tungsten tones mixing with cool blue and green neon signs, the subject lit predominantly by the warm tungsten with a creative color edge light from a distant blue neon sign creating a subtle cinematic teal/orange split, curious happy expression with wide eyes taking in the sensory richness of the market, skin tones rendered accurately under the difficult mixed warm light showing the camera's exceptional white balance intelligence, sharp face focus with excellent low-light eye detail and the bright market lights reflecting as multi-colored catchlights in the iris, vibrant blurred market bokeh background with hanging lanterns, signs, and crowd shapes creating a rich layered texture around the in-focus subject, fine steam or smoke from food stalls catching the neon light in the background adding atmospheric depth, travel documentary photography style that captures the authentic electric energy of a night market without flash photography, natural skin tones rendered correctly despite the impossible mixed-lighting situation",
  ],

};